### ISSUE TITLE
crash when whitespaces are on the [section] line

### ISSUE THREAD

**Issue by rveve** [albfan/bash-ini-parser#13]
This is a great tool, keep the good work but seems crashing if [section] lines have ending white spaces.

```
[section]     white spaces
k1=v1
k2=v2
```

> bash-ini-parser: eval: line 68: syntax error near unexpected token `)'

**Comment by albfan** [comment]
It must be something else. I modify whitespace test specifically for that d73cdd267db9e8f65972205c617db1f5710baa89 and still it passes
https://travis-ci.org/albfan/bash-ini-parser/builds/334045648

Feel free to add a PR with a failed test or add here your input file (a representative one), and output using

    BASH_INI_PARSER_DEBUG=1 cfg_parser <your-file.ini>

**Comment by albfan** [comment]
test coverage for whitespace is complete and now test is fixed on mac (bash 3 really) I don't even need to ask about your environment to be sure this issue is fixed.

In any case, if you're still interested on this issue anf for whatever reason it is not working for you, feel free to add more info so we can reopen it.
