### ISSUE TITLE
License

### ISSUE THREAD

**Issue by grembo** [albfan/bash-ini-parser#40]
As you derived your work from an MIT licensed code snippet, you might consider licensing this under an MIT (or similarly permissive) license.

**Comment by albfan** [comment]
Probably better ask directtly @ajdiaz, I'm not sure why you suppose that code snippet is licensed under MIT

Personally I prefer GPL3

**Comment by ajdiaz** [comment]
Hi!

This question back to me time to time. When I wrote the snippet I did not set any License. The reason was because it was intended to be just only a blog post and an idea of how to implement an INI parser in bash. But things go further some time after.

In a comment at the [blog post](https://web.archive.org/web/20180124065211/theoldschooldevops.com/2008/02/09/bash-ini-parser/) I decided to use MIT license to the snippet to ensure that there was no restrictions to the use. So, let's say that the license is MIT.

Anyway, for me is OK if you use it in your GPL3 code under that license, so feel free to use it without problems.

-- AJ

**Comment by grembo** [comment]
> Probably better ask directtly @ajdiaz, I'm not sure why you suppose that code snippet is licensed under MIT
> 

This comment on the blog post:

<img width="800" alt="Screen Shot 2021-05-08 at 16 16 12" src="https://user-images.githubusercontent.com/5884220/117542420-df7ac200-b018-11eb-9f82-28ae72816af3.png">

> Personally I prefer GPL3

That's of course of up to you (you can take any MIT/BSD/etc. licensed code and use it in a project that doesn't grant the same liberties these licenses grant - it's just less useful to others that way). Hence "you might consider" and not "you're not allowed to/you must". :)

**Comment by albfan** [comment]
Thanks @ajdiaz.

@grembo if less liberty means not being able to close source a project that uses this, I'm totally fine with that.

I don't want to promote in any way closed source code.

This project is a perfect example on how shared code and ideas can turn into something real and useful.

**Comment by grembo** [comment]
> This project is a perfect example on how shared code and ideas can turn into something real and useful.

It's also a perfect example how a permissive license didn't stop this from happening at all 😄
But in the end, this is kind of a philosophical question that can't be resolved through discussion (at least not here), so let's leave it at that.

Thank you both for your swift responses.
